Added GetDLRDeviceType api
neo-ai/neo-ai-dlr pull request #240
Opened 2020-09-24 23:34 UTC by cnv1989

Added APIs to expose DeviceType from metadata of compilation.

Thanks for contributing to DLR! By submitting this pull request, you confirm that your contribution is made under the terms of the [Apache 2.0 license](https://github.com/neo-ai/neo-ai-dlr/blob/master/LICENSE).

Please refer to our [guideline](https://github.com/neo-ai/neo-ai-dlr/blob/master/CONTRIBUTING.md) for useful information and tips.

2020-09-25 17:41 UTC, trevor-m requested changes
Thanks @cnv1989 ! Could you also add a check so that if the device type is available from the metadata but the user provides the wrong device type we give an error message? Somewhere in `SetupTVMModule`, `SetupTreeliteModule`, etc. Maybe make a helper function in DLRModel base class like `VerifyDeviceTypeIfAvailable()`.

2020-09-25 17:41 UTC, trevor-m commented on include/dlr_hexagon/dlr_hexagon.h
> +std::string GetHexagonModelFile(const std::string& dirname);
Duplicated line?

2020-09-25 17:41 UTC, trevor-m commented on src/dlr_hexagon/dlr_hexagon.cc
> +  LOG(INFO) << "libhexagon_nn_skel.so file is not found under folder: "
This message looks out of place

2020-09-25 17:41 UTC, trevor-m commented on src/dlr_common.cc
> +    const std::string &target_backend = metadata_.at("Requirements")
`const std::string &target_backend` -> `const std::string& target_backend`

2020-09-25 17:57 UTC, trevor-m requested changes

2020-09-25 17:57 UTC, trevor-m commented on src/dlr_common.cc
> +  } else if (target_backend == "mali") {
Mali should be `kDLOpenCL`

2020-09-25 18:44 UTC, trevor-m approved these changes

2020-09-25 20:33 UTC, merged

2020-10-15 00:09 UTC, apivovarov commented
WITH_HEXAGON build is broken https://github.com/neo-ai/neo-ai-dlr/issues/251