Used model_path to infer device type instead of model instance.
neo-ai/neo-ai-dlr pull request #242
Opened 2020-10-02 21:04 UTC by cnv1989

Thanks for contributing to DLR! By submitting this pull request, you confirm that your contribution is made under the terms of the [Apache 2.0 license](https://github.com/neo-ai/neo-ai-dlr/blob/master/LICENSE).

Please refer to our [guideline](https://github.com/neo-ai/neo-ai-dlr/blob/master/CONTRIBUTING.md) for useful information and tips.

2020-10-05 18:22 UTC, trevor-m approved these changes

2020-10-05 18:23 UTC, trevor-m requested changes

2020-10-05 18:23 UTC, trevor-m commented on include/dlr_common.h
> +const DLDeviceType GetDeviceTypeFromMetadata(std::vector<std::string> model_paths);
Make a const reference

2020-10-05 18:24 UTC, cnv1989 commented on include/dlr_common.h
> +const DLDeviceType GetDeviceTypeFromMetadata(std::vector<std::string> model_paths);
👍

2020-10-05 18:46 UTC, trevor-m approved these changes

2020-10-05 19:47 UTC, merged

2020-10-15 00:09 UTC, apivovarov commented
WITH_HEXAGON build is broken https://github.com/neo-ai/neo-ai-dlr/issues/251