Add compilation options for datatransform dependencies in dlr_relayvm.cc
neo-ai/neo-ai-dlr pull request #334
Opened 2021-03-17 18:18 UTC by yunma10

-Fix Typo in CMakeList.txt
-Compilation options for datatransform dependencies in dlr_relayvm.cc

2021-03-17 18:28 UTC, minlu1021 approved these changes

2021-03-17 20:47 UTC, trevor-m requested changes
Thanks @yunma10 

Could you enable data transform in CI build so that the tests are still ran.
https://github.com/neo-ai/neo-ai-dlr/blob/main/Jenkinsfile#L94

2021-03-18 00:27 UTC, trevor-m requested changes

2021-03-18 00:27 UTC, trevor-m commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_DATATRANSFORM")
Could you use `add_definitions(-DENABLE_DATATRANSFORM)` instead of CXX flags?

2021-03-18 00:28 UTC, trevor-m requested changes

2021-03-18 00:28 UTC, trevor-m commented on CMakeLists.txt
> +    file(GLOB HEXAGON_TEST_SRS tests/cpp/dlr_hexagon/*.cc)
Typo SRS -> SRCS?

2021-03-18 18:13 UTC, trevor-m requested changes

2021-03-18 18:13 UTC, trevor-m commented on CMakeLists.txt
> +message(${CMAKE_CXX_FLAGS})
Remove?

2021-03-18 18:20 UTC, trevor-m approved these changes

2021-03-18 19:15 UTC, merged